import {
  IconArrowUpRightCircle,
  IconCash,
  IconCopy,
  IconWallet,
  IconX,
} from "@tabler/icons";
import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import RightSidebar from "../components/RightSidebar";
import Tabs from "../components/Tabs";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [show, setShow] = useState(true);

  return (
    <div className={styles.container}>
      <Head>
        <title>NurtureLabs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.section}>
        <header
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
          }}>
          <span className="underline">Section</span>
          <div className={styles.wallet}>
            <IconWallet />
            <span>0.2 $XYZ</span>
            <div className={styles.badge}>Tier 1</div>
          </div>
        </header>
        {show ? (
          <div className={[styles.card, styles.tutorial].join(" ")}>
            <span style={{ width: "80%" }}>
              Lorem Ipsum is simply dummy text of the printing and typesetting
              industry.
            </span>
            <div>
              <button className={styles.tutBtn}>Tutorial</button>
            </div>
            <img src={"/assets/11.png"} className={styles.image} />
            <button className={styles.cross} onClick={() => setShow(false)}>
              <IconX size={15} />
            </button>
          </div>
        ) : (
          <button className={styles.tutBtn} onClick={() => setShow(true)}>
            Show tutorial
          </button>
        )}
        <div className={styles.card}>
          <span>Your rewards</span>
          <div
            style={{
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
            }}>
            <h2>$ 0.26231428</h2>
            <button className="primary-btn">
              <IconArrowUpRightCircle />
              <span>Custom Link</span>
            </button>
          </div>
          <div className={styles.pills}>
            <span className={styles.pill}>$40 AVAX</span>
            <span className={styles.pill}>$10 BNB</span>
            <span className={styles.pill}>$210 BTC</span>
          </div>
        </div>
        <div className={styles.cardContainer}>
          {Array(2)
            .fill(0)
            .map((_, idx) => (
              <div key={idx} className={styles.card}>
                <div style={{ display: "flex", alignItems: "center" }}>
                  <div className={styles.fee}>
                    <IconCash />
                  </div>
                  <h3 style={{ margin: 0 }}>12.5% of fee</h3>
                </div>
                <div
                  style={{
                    fontFamily: "Inter",
                    color: "#808191",
                    margin: "20px 0",
                  }}>
                  Your Referral Link for xyz
                </div>
                <div className={styles.referral}>
                  <span>https://unityexchange.design</span>
                  <IconCopy style={{ marginLeft: "auto" }} />
                </div>
              </div>
            ))}
        </div>
        <Tabs />
      </div>
      <RightSidebar />
    </div>
  );
};

export default Home;
